service: colecao_miniatura

image: ghcr.io/guiyones/colecao-miniatura

servers:
  web:
    - 138.199.239.103

ssh:
  user: sarandi

proxy:
  ssl: true
  host: app.example.com

registry:
  server: ghcr.io
  username: guiyones
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "hot_wheels_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64


accessories:
  db:
    image: postgres:16
    host: 138.199.239.103
    volumes: 
      - db: /var/lib/postgresql/miniaturas
    env:
      clear:
        POSTGRES_PORT: 5432
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB

volumes:
  db: {}
